django/adminSite/adminSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recordStoreAdmin.urls")),
]

django/adminSite/recordStoreAdmin/urls.py
from django.urls import path

from . import views

app_name = "recordStoreAdmin"
urlpatterns = [
    path("<str:token>", views.index, name="index"),
    path("add_record/<str:token>", views.add_record, name="add_record"),
]

django/adminSite/recordStoreAdmin/models.py
from django.db import models


class Addresses(models.Model):
    address_id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=45)
    zipcode = models.CharField(max_length=45)
    user = models.ForeignKey("Users", models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "Addresses"


class Genres(models.Model):
    genre_id = models.AutoField(primary_key=True)
    genre = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = "Genres"


class Artists(models.Model):
    artist_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = "Artists"


class Records(models.Model):
    record_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=45)
    price = models.IntegerField()
    stock = models.IntegerField()
    year = models.IntegerField()
    image = models.CharField(max_length=50000)
    genre = models.ForeignKey(Genres, models.DO_NOTHING)
    artist = models.ForeignKey(Artists, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "Records"


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    datetime = models.DateTimeField()
    status = models.TextField()
    price = models.IntegerField()
    address = models.ForeignKey(Addresses, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "Orders"

    def __str__(self):
        return str(self.price) + "$ - " + self.address.address


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=45)
    name = models.CharField(max_length=45)
    lastname = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    password = models.CharField(max_length=150)
    phone = models.CharField(max_length=45)
    admin = models.IntegerField()

    class Meta:
        managed = False
        db_table = "Users"


class Carts(models.Model):
    order_record_id = models.AutoField(primary_key=True)
    order = models.ForeignKey("Orders", models.DO_NOTHING)
    record = models.ForeignKey("Records", models.DO_NOTHING)
    quantity = models.IntegerField()

    class Meta:
        managed = False
        db_table = "Carts"

django/adminSite/recordStoreAdmin/forms.py
from django.forms import ModelForm, Form
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import django.forms as forms
from .models import Records


class RecordForm(ModelForm):
    class Meta:
        model = Records
        fields = ["title", "price", "stock", "genre", "artist", "year", "image"]


class OrderForm(forms.Form):
    order_id = forms.IntegerField()

django/adminSite/recordStoreAdmin/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Genres, Artists, Records, Orders, Carts, Users
from .forms import RecordForm, OrderForm
from django.contrib.auth import login
import jwt


def index(request, token):
    admin = is_admin(token)
    # if is_admin(token):
    order_list = Orders.objects.filter(status="0")
    if request.method == "POST":
        form = OrderForm(data=request.POST)

        if form.is_valid():
            orderId = form.cleaned_data["order_id"]
            items = Carts.objects.filter(order=orderId)
            for item in items:
                record = Records.objects.get(pk=item.record_id)
                record.stock = record.stock - item.quantity
                record.save(update_fields=["stock"])
            order = Orders.objects.get(pk=orderId)
            order.status = 1
            order.save()
            return redirect("/" + token)
        else:
            return render(
                request,
                "recordStoreAdmin/index.html",
                {
                    "form": form,
                    "order_list": order_list,
                    "token": token,
                    "error": form.errors.items,
                },
            )
    else:
        form = OrderForm()
        return render(
            request,
            "recordStoreAdmin/index.html",
            {"form": form, "token": token, "order_list": order_list},
        )


# else:
#   return HttpResponse("Forbidden")


def add_record(request, token):
    # if is_admin(token):
    genre_list = Genres.objects.all()
    artist_list = Artists.objects.all()
    if request.method == "POST":
        form = RecordForm(request.POST)

        if form.is_valid():
            r = Records(
                title=form.cleaned_data["title"],
                stock=form.cleaned_data["stock"],
                price=form.cleaned_data["price"],
                genre=form.cleaned_data["genre"],
                artist=form.cleaned_data["artist"],
                year=form.cleaned_data["year"],
                image=form.cleaned_data["image"],
            )
            r.save()
            return redirect("/add_record/" + token)
        else:
            return render(
                request,
                "recordStoreAdmin/add_record.html",
                {
                    "form": form,
                    "token": token,
                    "genre_list": genre_list,
                    "artist_list": artist_list,
                    "error": form.errors.items,
                },
            )
    else:
        form = RecordForm()
        return render(
            request,
            "recordStoreAdmin/add_record.html",
            {
                "form": form,
                "token": token,
                "genre_list": genre_list,
                "artist_list": artist_list,
            },
        )
    # else:
    #   return HttpResponse("Forbidden")


def is_admin(token):
    try:
        decoded = jwt.decode(token, "osecamgolasi")
        print(
            decoded
            + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        )
        u = Users.objects.get(pk=decoded["user_id"])
        if u.admin == 1:
            return True
        return False
    except:
        return False

django/adminSite/recordStoreAdmin/templates/recordStoreAdmin/add_record.html
{% extends 'master.html' %} {% block content %} {% if error %} {% for field, errors in error %} {% for e in errors %}
<div class="alert alert-danger" role="alert">
    {{field}} : {{e}}
</div>
{% endfor %} {% endfor %} {% endif %}
<h1>Add record</h1>
<form action="{% url 'recordStoreAdmin:add_record' token %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <labelclass="form-label">Genre</label>
            <select name="genre" class="form-select" aria-label="Default select example">
            {% for g in genre_list %}
            <option value="{{g.genre_id}}">{{g.genre}}</option>
            {% endfor %}
          </select>
    </div>
    <div class="mb-3">
        <labelclass="form-label">Artist</label>
            <select name="artist" class="form-select" aria-label="Default select example">
            {% for a in artist_list %}
            <option value="{{a.artist_id}}">{{a.name}}</option>
            {% endfor %}
          </select>
    </div>
    <div class="mb-3">
        <labelclass="form-label">Title</label>
            <input type="text" class="form-control" name="title">
    </div>
    <div class="mb-3">
        <labelclass="form-label">Year</label>
            <input type="number" class="form-control" name="year">
    </div>
    <div class="mb-3">
        <labelclass="form-label">Price</label>
            <input type="number" class="form-control" name="price">
    </div>
    <div class="mb-3">
        <labelclass="form-label">Image</label>
            <input type="text" class="form-control" name="image">
    </div>
    <div class="mb-3">
        <labelclass="form-label">Stock</label>
            <input type="number" class="form-control" name="stock">
    </div>
    <input type="submit" value="Save">
</form>
{% endblock %}

django/adminSite/recordStoreAdmin/templates/recordStoreAdmin/index.html
{% extends 'master.html' %} {% block content %} {% if error %} {% for field, errors in error %} {% for e in errors %}
<div class="alert alert-danger" role="alert">
    {{field}} : {{e}}
</div>
{% endfor %} {% endfor %} {% endif %}
<h1>Confirm orders</h1>
<form action="{% url 'recordStoreAdmin:index' token %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <labelclass="form-label">Orders</label>
            <select name="order_id" class="form-select" aria-label="Default select example">
            {% for o in order_list %}
            <option value="{{o.order_id}}">{{o}}</option>
            {% endfor %}
          </select>
    </div>
    <input type="submit" value="Save">
</form>
{% endblock %}

django/adminSite/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
             
      </ul>
    </div>
    <div class="form-inline my-2 my-lg-0">
        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
        {% else %}
            <a class="nav-link" href="/accounts/login">Login</a>
        {% endif %}
    </div>
  </nav>

django/adminSite/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    </head>

    <body>
        {% include 'header.html' %}
        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>
    </body>
</html>